# -*- coding: utf-8 -*-
"""conditional_statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mE1LiiijsROM9bnj4OdJcI7DqhTJavBp
"""

# conditional statement are used to make descisons
# three types of conditional statements
# if, elif, else

grade = 80
if grade >= 65:
    print("passed")
else:
    print("failed")

color = "green"
if color == "red":
    print("There is a wide range of red items available in the store.")
elif color == "green":
    print("There are a few green items available in the store.")
elif color == "blue":
    print("Very few items in blue color are available.")
else:
    print("There are no items of that color available in the store")

