# -*- coding: utf-8 -*-
"""python_data_types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v88knp0mXpwtMRdijZblnZlDD6tAg8UT
"""

#String
 #Storing names, messages, addresses, any text.
# Printing text for the user.
#Taking input from users

Greetings = "Good morning"
question = "How can I help you?"
print(Greetings)
print(question)

# Use of Integer
# represents whole numbers
# Counting or indexing
# Doing math calculations
# Storing ages, number of items, scores, etc.

#Example
x = 5
y= x * 3
print(y)

#use of float
#deals with height, weight, temperature etc.
#when percision is important

quantity = 20
price = 45.89
total = quantity * price
print("You bought", quantity , "watches for", total, "dollars")

total_salary = 10000
Employees = 5
salary_per_employee = total_salary / Employees
print("Each employee gets a salary of $", salary_per_employee, "per month.")

Math = 90
Science = 80
English = 85.5
History = 75

total_grades = Math + Science + English + History
Average = total_grades / 4
print("Your total grades are", total_grades, "and your average is", Average)

#taking inputs
num1= int(input("Enter first number  "))
num2= int(input("Enter second number  "))
print(num1 + num2)